#define ACTION_MOVE_FORWARD 0
#define ACTION_MOVE_LEFT 1
#define ACTION_MOVE_RIGHT 2
#define ACTION_MOVE_BACKWARD 3
#define ACTION_SPRINT 4
#define ACTION_MOVE_UP 5
#define ACTION_MOVE_DOWN 6
#define ACTION_CROUCH 7